// even or odd checker in JavaScript
const num = 5;
{
  if (num % 2 === 0) {
    console.log(`${num} is even`);
  } else {
    console.log(`${num} is odd`);
  }
}
// given a number, check if it is even or odd and print the result


let apple = 4;

if (apple % 2 === 0) {
  console.log(`${apple} is even`);
} else {
  console.log(`${apple} is odd`);
}

if (apple % 2 === 0) {
  console.log(`${apple} is even`);
} else {
  console.log(`${apple} is odd`);
}